let a = 2
pen down

face { move a turnY 90 move a turnY 90 move a turnY 90 move a turnY 90 }
move a
turnX -90

face { move a turnY 90 move a turnY 90 move a turnY 90 move a turnY 90 }
move a
turnX -90

face { move a turnY 90 move a turnY 90 move a turnY 90 move a turnY 90 }
move a
turnX -90

face { move a turnY 90 move a turnY 90 move a turnY 90 move a turnY 90 }
move a
turnX -90

turnZ 90
face { move a turnY 90 move a turnY 90 move a turnY 90 move a turnY 90 }
turnZ 90

pen up
turnY -90
move a
turnY 90
pen down

turnZ -90
face { move a turnY 90 move a turnY 90 move a turnY 90 move a turnY 90 }