print (999999)

int a = +3
print (a)

int b = 2 + +2
print (b)

int c = 10 - -5
print (c)

5
a + b
+10
a == b
print (7/2 + 3, "powinno byc 6") 

int licznik_petli = 0

for (int i = 0; i < 3; i = i + 1) {
    for (int j = 0; j < 3; j = j + 1) {
        licznik_petli = licznik_petli + 1
    }
}
print (licznik_petli)


int suma_k = 0
for (int k = 0; k < 6; k = k + 1) {
    print (k)
    suma_k = suma_k + k
    k = k + 1
}

print (suma_k)


pen down
move a
turnY 90
move b